using Station46.Runtime;
using UnityEngine;

namespace Station46.Dispenser.Scripts
{
    [RequireComponent(typeof(Rigidbody), typeof(Collider), typeof(Emission))]
    public class DispenserOrb : MonoBehaviour
    {
        public Color Color
        {
            set => _emission.color = value;
        }

        private Emission _emission;

        private void Awake()
        {
            _emission = GetComponent<Emission>();
        }

        private void Start()
        {
            _emission.active = true;
        }
    }
}